
spring:
  profiles:
    active:
    - default
  application:
    name: Cloud-Gateway
  cloud:
    gateway:
      routes:
      - id: person-controller
        uri: http://localhost:8080
        predicates:
        - Path=/person, /person/{segment}, /persons
      - id: swagger
        uri: http://localhost:8080
        predicates:
        - Path= /swagger-ui.html**, /webjars/**, /swagger-resources/**, /v2/api-docs

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
server:
  port: 8081